"""Adding count on metadata to support Performance Test Fix 2

Revision ID: 0024bacf3969
Revises: 804ecda3d5bf
Create Date: 2024-05-16 07:04:18.100165

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0024bacf3969"
down_revision = "804ecda3d5bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "testcasemetadata",
        "count",
        existing_type=sa.INTEGER(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "testcasemetadata",
        "count",
        existing_type=sa.Text(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
