"""Adding count on metadata to support Performance Test

Revision ID: 0a251edfd975
Revises: 96ee37627a48
Create Date: 2024-05-16 06:36:51.663230

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a251edfd975"
down_revision = "e2c185af1226"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("testcasemetadata", sa.Column("count", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("testcasemetadata", "count")
    # ### end Alembic commands ###
