#
# Copyright (c) 2023 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Add Errors To TestCases and Testsuites

Revision ID: 31f2da69d8c4
Revises: 94d307a738ba
Create Date: 2021-05-11 23:05:08.049029

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "31f2da69d8c4"
down_revision = "94d307a738ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "testcaseexecution",
        sa.Column("errors", sa.ARRAY(sa.String(), dimensions=1), nullable=True),
    )
    op.add_column(
        "testsuiteexecution",
        sa.Column("errors", sa.ARRAY(sa.String(), dimensions=1), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("testsuiteexecution", "errors")
    op.drop_column("testcaseexecution", "errors")
    # ### end Alembic commands ###
