"""Adding count on metadata to support Performance Test Fix 3

Revision ID: 585a78b2ebb8
Revises: 0024bacf3969
Create Date: 2024-05-16 07:09:32.071851

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "585a78b2ebb8"
down_revision = "0024bacf3969"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("testcasemetadata", "count", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "testcasemetadata", "count", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
