#
# Copyright (c) 2023 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Added archive support Project, TestRunExecution

Revision ID: 66f5fdf75be8
Revises: f5af3855be39
Create Date: 2022-01-19 09:38:22.325528

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "66f5fdf75be8"
down_revision = "f5af3855be39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("archived_at", sa.DateTime(), nullable=True))
    op.add_column(
        "testrunexecution", sa.Column("archived_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("testrunexecution", "archived_at")
    op.drop_column("project", "archived_at")
    # ### end Alembic commands ###
