#
# Copyright (c) 2023 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Added log to run

Revision ID: 94d307a738ba
Revises: ff250c32cf31
Create Date: 2021-04-20 14:41:08.377934

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "94d307a738ba"
down_revision = "ff250c32cf31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "testrunexecution",
        sa.Column("log", sa.JSON(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("testrunexecution", "log")
    # ### end Alembic commands ###
