#
# Copyright (c) 2023 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""added test metadata

Revision ID: b173743bd652
Revises: d4867f3a4c0a
Create Date: 2020-10-21 19:12:57.522433

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b173743bd652"
down_revision = "d4867f3a4c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "testcasemetadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("source_hash", sa.VARCHAR(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_testcasemetadata")),
    )
    op.create_index(
        op.f("ix_testcasemetadata_id"), "testcasemetadata", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_testcasemetadata_source_hash"),
        "testcasemetadata",
        ["source_hash"],
        unique=False,
    )
    op.create_table(
        "testsuitemetadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("source_hash", sa.VARCHAR(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_testsuitemetadata")),
    )
    op.create_index(
        op.f("ix_testsuitemetadata_id"), "testsuitemetadata", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_testsuitemetadata_source_hash"),
        "testsuitemetadata",
        ["source_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_testsuitemetadata_source_hash"), table_name="testsuitemetadata"
    )
    op.drop_index(op.f("ix_testsuitemetadata_id"), table_name="testsuitemetadata")
    op.drop_table("testsuitemetadata")
    op.drop_index(
        op.f("ix_testcasemetadata_source_hash"), table_name="testcasemetadata"
    )
    op.drop_index(op.f("ix_testcasemetadata_id"), table_name="testcasemetadata")
    op.drop_table("testcasemetadata")
    # ### end Alembic commands ###
