name: "Check spelling"
on: # rebuild any PRs and main branch changes
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop
      - main
jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          incremental_files_only: false
